#!/usr/bin/env bash

# Custom 'pre-build' hook for Docker Hub's automated builds.
# See https://docs.docker.com/docker-hub/builds/advanced/

echo "---- PRE-BUILD HOOK BEGIN ----"
printenv
echo "Current directory: $(pwd)"
ls -l -a
echo "Docker Images (all):"
docker image ls --all
echo "---- PRE-BUILD HOOK END ----"
